# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_app_pages.ipynb.

# %% auto 0
__all__ = ['LoginScreen']

# %% ../nbs/03_app_pages.ipynb 1
from fastcore.utils import *
from fasthtml.common import *
from fasthtml.jupyter import *
from fastlite import *
import fasthtml.components as fc
from fasthtml.common import A, Button as FhButton, I, Span
from .foundations import normalize_tokens, stringify, VEnum
from .core import *
from .components import *



# %% ../nbs/03_app_pages.ipynb 4
def LoginScreen(
    title='Sign In',
    subtitle='Choose your preferred sign-in method',
    providers=None,      
    left_slot=None,      
    logo_src=None,       
    testimonial_text=None, 
    brand_bg_cls='primary',
    left_cols=9,  # Number of columns for left side (out of 12), default 9 = 75%
    cls='',
    **kwargs
):
    """
    A configurable Split Login Screen using strict 'Fat Matt UI' helpers.
    
    Args:
        left_cols: Number of columns (out of 12) for the left brand section. 
                   Common values: 6 (50%), 7 (58%), 8 (67%), 9 (75%), 10 (83%)
    """
    
    # 1. Defaults
    if providers is None:
        providers = [
            {'label': 'Continue with Google', 'icon': 'https://authjs.dev/img/providers/google.svg', 'href': '/auth/google', 'cls': 'border responsive surface'},
            {'label': 'Continue with GitHub', 'icon': 'https://authjs.dev/img/providers/github.svg', 'icon_cls': 'invert', 'href': '/auth/github', 'cls': 'fill responsive inverse-surface'}
        ]

    # 2. Build Left Column
    if left_slot:
        left_content = left_slot
    else:
        default_content = []
        if logo_src: 
            default_content.append(Img(src=logo_src, cls="responsive margin-bottom", style="max-height: 60px"))
        if not logo_src and not testimonial_text:
            default_content.append(H3("Welcome", cls="center-align white-text"))
        if testimonial_text:
            default_content.append(Blockquote(P(f'"{testimonial_text}"', cls="italic center-align white-text")))
            
        # USER HELPER: DivCentered handles the alignment and spacing
        # Wrap in a Div with max-width, then center it
        left_content = Div(
            DivCentered(*default_content),
            style="max-width: 400px"
        )

    # 3. Build Right Column Buttons
    button_list = []
    for p in providers:
        icon = Img(src=p['icon'], cls=f"circle tiny spacing-right {p.get('icon_cls', '')}") if p.get('icon') else ""
        button_list.append(
            A(
                Button(icon, Span(p['label']), cls=p.get('cls')), 
                href=p.get('href', '#'),
                style="text-decoration: none; display: block;" 
            )
        )

    # USER HELPER: DivVStacked handles the vertical list + gap
    auth_buttons = DivVStacked(
        *button_list,
        cls="w-full"
    )

    # Wrap in a Div with max-width, then center it
    right_content = Div(
        DivCentered(
            H4(title, cls="center-align bold margin-bottom"),
            P(subtitle, cls="center-align medium-text margin-bottom"),
            auth_buttons,
        ),
        style="max-width: 350px; width: 100%"
    )

    # 4. The Grid - Calculate column sizes based on percentage
    left_percent = (left_cols / 12) * 100
    right_percent = ((12 - left_cols) / 12) * 100
    
    # Use CSS Grid for precise percentage-based split (BeerCSS compatible)
    return Div(
        # Left (Brand) - Configurable width with primary background
        Div(
            DivCentered(left_content),
            cls=f"{brand_bg_cls} padding",
            style="display: flex; align-items: center; justify-content: center; min-height: 100vh;"
        ),
        # Right (Auth) - Remaining width
        Div(
            DivCentered(right_content),
            cls="padding",
            style="display: flex; align-items: center; justify-content: center; min-height: 100vh;"
        ),
        # Use CSS Grid to control the split with configurable percentages
        cls=cls,
        style=f"display: grid; grid-template-columns: {left_percent}% {right_percent}%; min-height: 100vh; margin: 0; padding: 0;",
        **kwargs
    )
