"""Pre-built page layouts for authenticated app experiences (login, dashboard, admin)."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_app_pages.ipynb.

# %% auto 0
__all__ = ['LoginScreen']

# %% ../nbs/03_app_pages.ipynb 2
from fastcore.utils import *
from fasthtml.common import *
from fasthtml.jupyter import *
from fastlite import *
import fasthtml.components as fc
from fasthtml.common import A, Button as FhButton, I, Span
from .foundations import normalize_tokens, stringify, VEnum
from .core import *
from .components import *



# %% ../nbs/03_app_pages.ipynb 7
def LoginScreen(
    title='Sign In',
    subtitle='Choose your preferred sign-in method',
    providers=None,      
    left_slot=None,      
    logo_src=None,       
    testimonial_text=None, 
    brand_bg_cls='primary',
    left_cols=9,  # Number of columns for left side (out of 12), default 9 = 75%
    cls='',
    **kwargs
):
    """
    A configurable Split Login Screen using strict BeerCSS helpers.
    
    Args:
        left_cols: Number of columns (out of 12) for the left brand section. 
                   Common values: 6 (50%), 7 (58%), 8 (67%), 9 (75%), 10 (83%)
    """
    
    # 1. Defaults
    if providers is None:
        providers = [
            {'label': 'Continue with Google', 'icon': 'https://authjs.dev/img/providers/google.svg', 'href': '/auth/google', 'cls': 'border responsive surface'},
            {'label': 'Continue with GitHub', 'icon': 'https://authjs.dev/img/providers/github.svg', 'icon_cls': 'invert', 'href': '/auth/github', 'cls': 'fill responsive inverse-surface'}
        ]

    # 2. Build Left Column
    if left_slot:
        left_content = left_slot
    else:
        default_content = []
        if logo_src: 
            default_content.append(Img(src=logo_src, cls="responsive small margin-bottom"))
        if not logo_src and not testimonial_text:
            default_content.append(H3("Welcome", cls="center-align white-text"))
        if testimonial_text:
            default_content.append(Blockquote(P(f'"{testimonial_text}"', cls="italic center-align white-text")))
            
        # USER HELPER: DivCentered handles the alignment and spacing
        left_content = Div(
            DivCentered(*default_content),
            cls="small-width"
        )

    # 3. Build Right Column Buttons
    button_list = []
    for p in providers:
        icon = Img(src=p['icon'], cls=f"circle tiny spacing-right {p.get('icon_cls', '')}") if p.get('icon') else ""
        button_list.append(
            Div(
                A(
                    Button(icon, Span(p['label']), cls=p.get('cls')), 
                    href=p.get('href', '#')
                ),
                cls="s12"
            )
        )

    # Use BeerCSS grid for proper stacking with spacing
    auth_buttons = Div(
        *button_list,
        cls="grid small-space"
    )

    right_content = Div(
        H4(title, cls="center-align bold margin-bottom"),
        P(subtitle, cls="center-align medium-text margin-bottom no-wrap"),
        auth_buttons,
        cls="medium-width"
    )

    # 4. The Grid - BeerCSS responsive grid (stacks on mobile, splits on desktop)
    right_cols = 12 - left_cols
    
    # Note: min-height: 100vh needed for full viewport - BeerCSS large-height isn't exact 100vh
    return Div(
        # Left (Brand) - Full width on mobile/tablet, configurable on desktop
        Div(
            DivCentered(left_content),
            cls=f"s12 m12 l{left_cols} {brand_bg_cls} padding middle-align center-align"
        ),
        # Right (Auth) - Full width on mobile/tablet, remaining cols on desktop
        Div(
            DivCentered(right_content),
            cls=f"s12 m12 l{right_cols} padding middle-align center-align"
        ),
        cls=f"grid no-space {cls}".strip(),
        style="min-height: 100vh;",
        **kwargs
    )
