# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_page_snippets.ipynb.

# %% auto 0
__all__ = ['LoginScreen', 'CookiesBanner']

# %% ../nbs/04_page_snippets.ipynb 1
from fastcore.utils import *
from fasthtml.common import *
from fasthtml.jupyter import *
from fastlite import *
import fasthtml.components as fc
from fasthtml.common import A, Button as FhButton, I, Span
from .foundations import normalize_tokens, stringify, VEnum
from .core import *
from .components import *



# %% ../nbs/04_page_snippets.ipynb 4
def LoginScreen(
    title='Sign In',
    subtitle='Choose your preferred sign-in method',
    providers=None,      
    left_slot=None,      
    logo_src=None,       
    testimonial_text=None, 
    brand_bg_cls='primary',
    left_cols=9,  # Number of columns for left side (out of 12), default 9 = 75%
    cls='',
    **kwargs
):
    """
    A configurable Split Login Screen using strict 'Fat Matt UI' helpers.
    
    Args:
        left_cols: Number of columns (out of 12) for the left brand section. 
                   Common values: 6 (50%), 7 (58%), 8 (67%), 9 (75%), 10 (83%)
    """
    
    # 1. Defaults
    if providers is None:
        providers = [
            {'label': 'Continue with Google', 'icon': 'https://authjs.dev/img/providers/google.svg', 'href': '/auth/google', 'cls': 'border responsive surface'},
            {'label': 'Continue with GitHub', 'icon': 'https://authjs.dev/img/providers/github.svg', 'icon_cls': 'invert', 'href': '/auth/github', 'cls': 'fill responsive inverse-surface'}
        ]

    # 2. Build Left Column
    if left_slot:
        left_content = left_slot
    else:
        default_content = []
        if logo_src: 
            default_content.append(Img(src=logo_src, cls="responsive margin-bottom", style="max-height: 60px"))
        if not logo_src and not testimonial_text:
            default_content.append(H3("Welcome", cls="center-align white-text"))
        if testimonial_text:
            default_content.append(Blockquote(P(f'"{testimonial_text}"', cls="italic center-align white-text")))
            
        # USER HELPER: DivCentered handles the alignment and spacing
        # Wrap in a Div with max-width, then center it
        left_content = Div(
            DivCentered(*default_content),
            style="max-width: 400px"
        )

    # 3. Build Right Column Buttons
    button_list = []
    for p in providers:
        icon = Img(src=p['icon'], cls=f"circle tiny spacing-right {p.get('icon_cls', '')}") if p.get('icon') else ""
        button_list.append(
            A(
                Button(icon, Span(p['label']), cls=p.get('cls')), 
                href=p.get('href', '#'),
                style="text-decoration: none; display: block;" 
            )
        )

    # USER HELPER: DivVStacked handles the vertical list + gap
    auth_buttons = DivVStacked(
        *button_list,
        cls="w-full"
    )

    # Wrap in a Div with max-width, then center it
    right_content = Div(
        DivCentered(
            H4(title, cls="center-align bold margin-bottom"),
            P(subtitle, cls="center-align medium-text margin-bottom"),
            auth_buttons,
        ),
        style="max-width: 350px; width: 100%"
    )

    # 4. The Grid - Calculate column sizes based on percentage
    left_percent = (left_cols / 12) * 100
    right_percent = ((12 - left_cols) / 12) * 100
    
    # Use CSS Grid for precise percentage-based split (BeerCSS compatible)
    return Div(
        # Left (Brand) - Configurable width with primary background
        Div(
            DivCentered(left_content),
            cls=f"{brand_bg_cls} padding",
            style="display: flex; align-items: center; justify-content: center; min-height: 100vh;"
        ),
        # Right (Auth) - Remaining width
        Div(
            DivCentered(right_content),
            cls="padding",
            style="display: flex; align-items: center; justify-content: center; min-height: 100vh;"
        ),
        # Use CSS Grid to control the split with configurable percentages
        cls=cls,
        style=f"display: grid; grid-template-columns: {left_percent}% {right_percent}%; min-height: 100vh; margin: 0; padding: 0;",
        **kwargs
    )

# %% ../nbs/04_page_snippets.ipynb 9
def CookiesBanner(
    message='We use cookies to enhance your experience. By continuing to visit this site you agree to our use of cookies.',
    accept_text='Accept',
    decline_text='Decline',
    settings_text=None,
    policy_link='/cookies',
    policy_text='Learn more',
    position='bottom',
    on_accept='console.log("Accepted")',
    on_decline='console.log("Declined")',
    on_settings='console.log("Settings")',
    cls='',
    **kwargs
):
    """
    Reusable cookie consent banner component.
    
    Args:
        message: Cookie policy message (default: standard message)
        accept_text: Accept button text (default: 'Accept')
        decline_text: Decline button text (default: 'Decline')
        settings_text: Optional settings button text (default: None)
        policy_link: Cookie policy page link (default: '/cookies')
        policy_text: Policy link text (default: 'Learn more')
        position: Banner position - 'top', 'bottom' (default: 'bottom')
        on_accept: JavaScript for accept (default: console.log)
        on_decline: JavaScript for decline (default: console.log)
        on_settings: JavaScript for settings (default: console.log)
        cls: Additional CSS classes
        **kwargs: Additional attributes
    
    Returns:
        Div component styled as cookie banner
    
    Examples:
        CookiesBanner()
        CookiesBanner(message='We use cookies', position='top')
        CookiesBanner(settings_text='Customize', on_accept='acceptCookies()')
    """
    # Build message with policy link
    message_content = Div(
        Span(message, cls='small-text'),
        ' ',
        A(policy_text, href=policy_link, cls=AT.primary),
        cls='max'
    )
    
    # Build action buttons
    buttons = []
    
    if decline_text:
        buttons.append(
            Button(
                decline_text,
                type='button',
                cls=ButtonT.secondary,
                onclick=f"{on_decline}; this.closest('.cookie-banner').remove();"
            )
        )
    
    if settings_text:
        buttons.append(
            Button(
                settings_text,
                type='button',
                cls=ButtonT.secondary,
                onclick=on_settings
            )
        )
    
    buttons.append(
        Button(
            accept_text,
            type='button',
            cls=ButtonT.primary,
            onclick=f"{on_accept}; this.closest('.cookie-banner').remove();"
        )
    )
    
    # Build banner content
    banner_content = Div(
        Icon('cookie', cls='medium'),
        message_content,
        Div(*buttons, cls='row'),
        cls='row middle-align'
    )
    
    # Position styling
    position_style = {
        'top': 'position: fixed; top: 0; left: 0; right: 0; z-index: 9999;',
        'bottom': 'position: fixed; bottom: 0; left: 0; right: 0; z-index: 9999;'
    }
    
    style = position_style.get(position, position_style['bottom'])
    
    # Build banner
    banner_cls = f'cookie-banner surface-container padding shadow {cls}'.strip()
    
    return Div(
        banner_content,
        cls=banner_cls,
        style=style,
        **kwargs
    )
