"""Complete page components for common web application patterns"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_landing_page.ipynb.

# %% auto 0
__all__ = ['HeroSection', 'FeaturesGrid', 'SplitFeatureStyles', 'SplitFeatureScript', 'SplitFeatureTextBlock',
           'SplitFeatureImageBlock', 'SplitFeature', 'PricingSection', 'FAQSection', 'PageFooter', 'LandingNavBar',
           'LandingPage', 'LandingPageV2_nav']

# %% ../nbs/05_landing_page.ipynb 2
import importlib



from .components import *
from .core import *
from fasthtml.common import *
from .page_snippets import *
from .foundations import *

from fastcore.utils import partial
from fasthtml.common import *
from fasthtml.jupyter import FastHTML, fast_app, JupyUvi, HTMX
from fastlite import *
import fasthtml.components as fc
from fasthtml.common import A, Button as FhButton, I, Span
import socket
import time
import subprocess

# %% ../nbs/05_landing_page.ipynb 5
def HeroSection(
    title: str,              # Main hero title
    subtitle: str,           # Hero subtitle/description
    primary_cta_text: str,   # Primary CTA button text
    primary_cta_href: str,   # Primary CTA button href
    secondary_cta_text: str = None,  # Secondary CTA button text (optional)
    secondary_cta_href: str = None,  # Secondary CTA button href (optional)
    background: str = "bg-primary-container",  # BeerCSS background class
    cls: str = "",  # Additional classes
    style: str | None = None,  # Optional inline style (avoid by default)
    extra_css: str | None = None,  # Optional custom CSS (minimal; opt-in)
    extra_js: str | None = None,  # Optional custom JS (minimal; opt-in)
 ):
    """Hero section (BeerCSS-first).
    
    Note: Avoid `middle-align` on the outer stack; in BeerCSS it can turn the
    wrapper into a horizontal flex row, which makes the H1/P/CTA sit side-by-side.
    """
    hooks = []
    if extra_css:
        hooks.append(Style(extra_css))
    if extra_js:
        hooks.append(Script(extra_js))
    
    ctas = [Button(primary_cta_text, href=primary_cta_href, variant="raised")]
    if secondary_cta_text and secondary_cta_href:
        ctas.append(Button(secondary_cta_text, href=secondary_cta_href, variant="outlined"))
    
    stack = DivVStacked(
        H1(title, cls="no-margin"),
        P(subtitle, cls="secondary-text"),
        Div(*ctas, cls="row middle-align center-align small-space"),
        cls="center-align large-padding",
    )
    content = Div(stack, cls="responsive")
    return Section(
        *hooks,
        content,
        cls=f"{background} {cls}".strip(),
        style=style,
    )

# %% ../nbs/05_landing_page.ipynb 10
def FeaturesGrid(
    features: list,  # List of dicts with 'icon', 'title', 'description'
    title: str = None,  # Optional section title
    subtitle: str = None,  # Optional section subtitle
    cols: int = 3,  # Number of columns (1-4)
    cls: str = ""  # Additional classes
):
    """Grid of feature cards using BeerCSS grid helpers."""
    import fh_matui.components as _cmp
    
    GridCell = getattr(_cmp, 'GridCell', None)
    ResponsiveGrid = getattr(_cmp, 'ResponsiveGrid', None)
    
    if GridCell is None or ResponsiveGrid is None:
        # Fallback: keep previews working even if the notebook kernel has a stale module import.
        def GridCell(*c, span=(), cls='', **kwargs):
            cell_cls = []
            cell_cls.extend(normalize_tokens(span))
            cell_cls.extend(normalize_tokens(cls))
            cell_cls = [t for t in cell_cls if t]
            return Div(*c, cls=stringify(dedupe_preserve_order(cell_cls)), **kwargs)
        
        def ResponsiveGrid(*cells, space='medium-space', cls: str = '', **kwargs):
            cls_tokens = normalize_tokens(cls)
            grid_cls = ['grid']
            if space and space not in cls_tokens:
                grid_cls.extend(normalize_tokens(space))
            grid_cls.extend(cls_tokens)
            grid_cls = [t for t in grid_cls if t]
            return Div(*cells, cls=stringify(dedupe_preserve_order(grid_cls)), **kwargs)
    
    cols = max(1, min(int(cols), 4))
    col_width = 12 // cols  # 12-col grid
    
    s_span = "s12"
    m_span = "m12" if cols == 1 else "m6"
    l_span = f"l{col_width}"
    cell_span = f"{s_span} {m_span} {l_span}".strip()
    
    cells = [
        GridCell(
            Card(
                Div(Icon(f["icon"], size="medium", cls="primary-text"), cls="center-align"),
                H5(f["title"], cls="center-align small-margin"),
                P(f["description"], cls="secondary-text center-align"),
                cls="center-align padding",
            ),
            span=cell_span,
        )
        for f in features
    ]
    
    content = []
    if title:
        content.append(H1(title, cls="center-align bottom-margin"))
    if subtitle:
        content.append(P(subtitle, cls="center-align secondary-text large-margin large-text"))
    
    content.append(ResponsiveGrid(*cells, space="medium-space"))
    return Section(*content, cls=f"padding horizontal-padding {cls}".strip())

# %% ../nbs/05_landing_page.ipynb 13
def SplitFeatureStyles():
    """CSS for smooth scroll-based fade-in animations (opt-in via SplitFeature_v1)."""
    return Style("""
        .fade-in-left {
            opacity: 0;
            transform: translateX(-30px);
            transition: opacity 0.8s ease-out, transform 0.8s ease-out;
        }
        
        .fade-in-right {
            opacity: 0;
            transform: translateX(30px);
            transition: opacity 0.8s ease-out, transform 0.8s ease-out;
        }
        
        .fade-in-left.visible,
        .fade-in-right.visible {
            opacity: 1;
            transform: translateX(0);
        }
    """)

def SplitFeatureScript():
    """JavaScript for scroll-triggered animations (opt-in via SplitFeature_v1)."""
    return Script("""
        const observer = new IntersectionObserver((entries) => {
            entries.forEach(entry => {
                if (entry.isIntersecting) {
                    entry.target.classList.add('visible');
                }
            });
        }, { threshold: 0.15, rootMargin: '0px 0px -50px 0px' });
        
        document.querySelectorAll('.fade-in-left, .fade-in-right').forEach(el => {
            observer.observe(el);
        });
    """)

#| export
def SplitFeatureTextBlock(
    eyebrow: str,
    title: str,
    description: str,
    anim_cls: str = "",
    cls: str = "",
    style: str | None = None,
    **kwargs,
    ):
    """SplitFeature text block (exported, testable)."""
    block_cls = f"column small-space {cls} {anim_cls}".strip()
    return Div(
        Small(eyebrow, cls="bold primary-text upper"),
        H3(title),
        P(description, cls="medium-text opacity-text"),
        cls=block_cls,
        style=style,
        **kwargs,
    )

#| export
def SplitFeatureImageBlock(
    image_src: str,
    alt: str,
    anim_cls: str = "",
    cls: str = "",
    style: str | None = None,
    **kwargs,
    ):
    """SplitFeature image block (exported, testable)."""
    block_cls = f"center-align {cls} {anim_cls}".strip()
    return Div(
        Img(src=image_src, alt=alt, cls="responsive round"),
        cls=block_cls,
        style=style,
        **kwargs,
    )

#| export
def SplitFeature(
    eyebrow: str,          # The small text above the headline
    title: str,            # The main headline
    description: str,      # The paragraph text
    image_src: str,        # URL for the image
    reverse: bool = False, # True = Image first, Text second
    animate: bool = False, # Animation is opt-in
    cls: str = "",
    style: str | None = None,  # Optional inline style (avoid by default)
    extra_css: str | None = None,  # Optional custom CSS (minimal; opt-in)
    extra_js: str | None = None,  # Optional custom JS (minimal; opt-in)
    block_cls: str = "",  # Additional classes for the inner wrapper
    text_cls: str = "",   # Extra classes for the text block
    image_cls: str = "",  # Extra classes for the image block
    ):
    """A split section (Text + Image) using BeerCSS (animation opt-in).
    
    Layout: two-column grid (roughly 60/40) using BeerCSS s/m/l spans.
    `reverse=True` swaps DOM order (image first).
    """
    hooks = []
    if animate:
        hooks.append(SplitFeatureStyles())
        hooks.append(SplitFeatureScript())
    if extra_css:
        hooks.append(Style(extra_css))
    if extra_js:
        hooks.append(Script(extra_js))
    
    text_anim = "fade-in-right" if (reverse and animate) else "fade-in-left" if animate else ""
    img_anim = "fade-in-left" if (reverse and animate) else "fade-in-right" if animate else ""
    
    text_block = SplitFeatureTextBlock(
        eyebrow=eyebrow,
        title=title,
        description=description,
        anim_cls=text_anim,
        cls=text_cls,
    )
    img_block = SplitFeatureImageBlock(
        image_src=image_src,
        alt=title,
        anim_cls=img_anim,
        cls=image_cls,
    )
    
    # 12-col: 7/5 ~= 58/42 (close to 60/40). Full-width stacking on small screens.
    text_cell = GridCell(text_block, span="s12 m7 l7")
    img_cell = GridCell(img_block, span="s12 m5 l5")
    content = [img_cell, text_cell] if reverse else [text_cell, img_cell]
    
    grid = ResponsiveGrid(*content, space="large-space", cls=f"middle-align {block_cls}".strip())
    # Default bottom margin prevents stacked SplitFeatures from visually overlapping/touching.
    return Section(
        *hooks,
        grid,
        cls=f"responsive large-padding bottom-margin {cls}".strip(),
        style=style,
    )

# %% ../nbs/05_landing_page.ipynb 18
def PricingSection(
    title: str,           # Section title
    monthly_price: str,   # Monthly price display
    yearly_price: str,    # Yearly price display
    plan_name: str,       # Name of the plan
    features: list,       # List of feature strings
    cta_text: str,        # CTA button text
    cta_href: str,        # CTA button href
    cls: str = "",        # Additional classes
    show_toggle: bool = False,  # When True, render HTMX toggle buttons
    monthly_url: str | None = None,  # HTMX endpoint for monthly pricing (opt-in)
    yearly_url: str | None = None,  # HTMX endpoint for yearly pricing (opt-in)
    price_target_id: str = "price-display",  # HTMX target element id
    style: str | None = None,  # Optional inline style (avoid by default)
    extra_css: str | None = None,  # Optional custom CSS (minimal; opt-in)
    extra_js: str | None = None,  # Optional custom JS (minimal; opt-in)
):
    """Pricing section (BeerCSS-first)."""
    hooks = []
    if extra_css:
        hooks.append(Style(extra_css))
    if extra_js:
        hooks.append(Script(extra_js))
    
    toggle_block = None
    if show_toggle and monthly_url and yearly_url:
        toggle_block = Div(
            Button(
                "Monthly",
                hx_get=monthly_url,
                hx_target=f"#{price_target_id}",
                hx_swap="innerHTML",
                variant="text",
            ),
            Button(
                "Yearly",
                hx_get=yearly_url,
                hx_target=f"#{price_target_id}",
                hx_swap="innerHTML",
                variant="text",
            ),
            cls="row middle-align center-align small-space",
        )
    
    feature_rows = [
        Li(
            Div(
                Icon("check", size="small"),
                Span(feature),
                cls="row middle-align small-space",
            )
        )
        for feature in features
    ]
    
    price_display = Div(id=price_target_id, cls="large-text bold")(
        Span(f"{monthly_price}/month"),
    )
    yearly_hint = P(f"{yearly_price}/year", cls="secondary-text") if yearly_price else None
    
    card = Card(
        H3(plan_name, cls="no-margin center-align"),
        Div(price_display, yearly_hint, cls="column center-align small-space"),
        Ul(*feature_rows, cls="column small-space"),
        Button(cta_text, href=cta_href, variant="raised"),
        cls="padding round",
    )
    
    return Section(
        *hooks,
        Div(
            H2(title, cls="center-align"),
            toggle_block,
            Div(card, cls="responsive"),
            cls="column center-align large-space",
        ),
        cls=f"large-padding {cls}".strip(),
        style=style,
    )

# %% ../nbs/05_landing_page.ipynb 20
def FAQSection(title: str, faqs: list, cls: str = ""):
    """FAQ section (BeerCSS-first)."""
    return Section(
        H2(title, cls="center-align bottom-margin"),
        *[
            Details(
                Summary(
                    Article(
                        Nav(Div(faq['question'], cls="max bold"), I("expand_more")),
                        cls="round primary no-elevate",
                    )
                ),
                Article(P(faq['answer'], cls="secondary-text"), cls="round border padding"),
            )
            for faq in faqs
        ],
        cls=f"responsive column large-space {cls}".strip(),
    )

# %% ../nbs/05_landing_page.ipynb 23
def PageFooter(
    columns: list,         # List of dicts with 'title' and 'links' (list of dicts with 'text' and 'href')
    copyright: str,        # Copyright text
    social_links: list = None,  # List of dicts with 'icon' and 'href'
    logo: str = None,      # Optional logo text
    cls: str = ""          # Additional classes
):
    """Footer with multiple columns, social links, and copyright"""
    footer_cols = []
    
    # Logo column if provided
    if logo:
        footer_cols.append(
            Div(
                H6(logo, cls='no-margin bold'),
                cls='padding'
            )
        )
    
    # Link columns
    for col in columns:
        links = [A(link['text'], href=link['href'], cls='grey-text') for link in col.get('links', [])]
        footer_cols.append(
            Div(
                H6(col['title'], cls='no-margin bold'),
                Div(*links, cls='column small-space'),
                cls='padding'
            )
        )
    
    # Footer row with full spacing between columns
    footer_row = DivFullySpaced(*footer_cols)
    
    # Bottom section with copyright and social links
    bottom_left = Div(P(copyright, cls='small-text grey-text no-margin'))
    
    bottom_right = Div()
    if social_links:
        social_icons = [A(Icon(s['icon']), href=s['href'], cls='grey-text') for s in social_links]
        bottom_right = Div(*social_icons, cls='row small-space')
    
    bottom_section = DivFullySpaced(bottom_left, bottom_right)
    
    footer_cls = f'surface-container padding {cls}'.strip()
    return ft_hx('footer')(
        Div(
            footer_row,
            Hr(),
            bottom_section,
            cls=f"responsive {footer_cls}"
        )
    )


# %% ../nbs/05_landing_page.ipynb 25
def LandingNavBar(
    brand_name: str,        # Brand name for the navbar
    links: list = None,     # List of dicts with 'text' and 'href'
    actions: list = None,   # List of action buttons (Buttons/Links)
    sticky: bool = True,    # Whether navbar sticks to top
    cls: str = ""           # Additional classes
):
    """
    Landing page navigation bar using Toolbar component with brand and links.
    
    Args:
        brand_name: Brand name/logo text
        links: List of navigation links [{'text': 'Features', 'href': '#features'}, ...]
        actions: List of action elements (Buttons, etc.) for CTA
        sticky: Whether navbar sticks to top while scrolling (default: True)
        cls: Additional CSS classes
    
    Example:
        LandingNavBar(
            brand_name="MyBrand",
            links=[
                {'text': 'Features', 'href': '#features'},
                {'text': 'Pricing', 'href': '#pricing'},
                {'text': 'FAQ', 'href': '#faq'}
            ],
            actions=[
                Button("Sign Up", href="/signup", variant="raised")
            ]
        )
    """
    # Build navigation elements
    nav_items = []
    
    # Add brand
    nav_items.append(H5(brand_name, cls="no-margin bold"))
    
    # Add spacer to push links to the right
    nav_items.append(Div(cls="max"))
    
    # Add navigation links
    if links:
        for link in links:
            nav_items.append(
                A(link['text'], href=link['href'], cls="padding")
            )
    
    # Add action buttons
    if actions:
        nav_items.extend(actions)
    
    # Use Toolbar with sticky positioning and blur effect
    toolbar_cls = f"blur {'sticky top' if sticky else ''} {cls}".strip()
    
    return Toolbar(Container(*nav_items, responsive=True), cls=toolbar_cls, fill=True, elevate='medium')

# %% ../nbs/05_landing_page.ipynb 27
def LandingPage(
    brand_name: str,        # Brand name for navbar
    hero_title: str,        # Hero section title
    hero_subtitle: str,     # Hero section subtitle
    features: list,         # Features list
    faqs: list,             # FAQ list
    demo_modal_id: str = "demo-modal",  # Kept for backward-compat; not used by default
    cls: str = ""           # Additional classes
):
    """Complete landing page (BeerCSS-first)."""
    nav = LandingNavBar(
        brand_name=brand_name,
        links=[
            {'text': 'Features', 'href': '#features'},
            {'text': 'Pricing', 'href': '#pricing'},
            {'text': 'FAQ', 'href': '#faq'},
        ],
        actions=[
            Button("Sign Up", href="/signup", variant="raised"),
        ],
    )
    hero = HeroSection(
        title=hero_title,
        subtitle=hero_subtitle,
        primary_cta_text="Get Started",
        primary_cta_href="/signup",
        secondary_cta_text="Learn More",
        secondary_cta_href="#features",
        background="bg-primary-container",
    )
    pricing = PricingSection(
        title="Simple Pricing",
        monthly_price="$7.99",
        yearly_price="$79.99",
        plan_name="Professional",
        features=["Unlimited projects", "24/7 support", "Advanced analytics", "Custom domain"],
        cta_text="Get Started",
        cta_href="/signup",
    )
    return Div(
        nav,
        hero,
        Div(
            Div(id="features")(
                FeaturesGrid(
                    features=features,
                    title="Why Choose Us",
                    subtitle="Everything you need to build amazing web apps",
                    cols=3,
                )
            ),
            Div(id="pricing")(pricing),
            Div(id="faq")(FAQSection(title="Frequently Asked Questions", faqs=faqs)),
            cls="responsive column large-space",
        ),
        PageFooter(
            columns=[
                {'title': 'Product', 'links': [
                    {'text': 'Features', 'href': '#features'},
                    {'text': 'Pricing', 'href': '#pricing'},
                ]},
                {'title': 'Company', 'links': [
                    {'text': 'About', 'href': '/about'},
                    {'text': 'Blog', 'href': '/blog'},
                    {'text': 'Contact', 'href': '/contact'},
                ]},
                {'title': 'Legal', 'links': [
                    {'text': 'Privacy', 'href': '/privacy'},
                    {'text': 'Terms', 'href': '/terms'},
                ]},
            ],
            copyright=f"© 2025 {brand_name}. All rights reserved.",
            social_links=[
                {'icon': 'twitter', 'href': 'https://twitter.com'},
                {'icon': 'github', 'href': 'https://github.com'},
                {'icon': 'linkedin', 'href': 'https://linkedin.com'},
            ],
            logo=brand_name,
        ),
        cls=f"column {cls}".strip(),
    )

# %% ../nbs/05_landing_page.ipynb 28
def LandingPageV2_nav(
    brand_name: str,
    links: list | None = None,
    cls: str = "",
) -> FastHTML:
    """Landing page V2 demo (BeerCSS-first).

    Focus: all content sits inside a centered container (not full width).
    """
    nav_links = links or [
        {"text": "Overview", "href": "#overview"},
        {"text": "Features", "href": "#features"},
        {"text": "Pricing", "href": "#pricing"},
    ]

    link_items = [A(item["text"], href=item["href"], cls="padding") for item in nav_links]

    toolbar = Toolbar(
        Div(
            H5(brand_name, cls="no-margin bold"),
            Div(cls="max"),
            *link_items,
            cls="row wrap middle-align fully-spaced",
        ),
        cls="round surface-container-highest blur shadow-medium",
        fill=True,
        elevate="medium",
    )

    hero_section = HeroSection(
        title="Build faster with FastHTML",
        subtitle="Compose production-ready pages with Material inspired components wired for HTMX.",
        primary_cta_text="Get Started",
        primary_cta_href="/signup",
        secondary_cta_text="View Docs",
        secondary_cta_href="/docs",
        background="bg-primary-container",
        cls="round shadow-medium",
    )

    feature_highlights = Section(
        Div(
            Small("Workflow", cls="primary-text upper bold"),
            H2("Opinionated building blocks", cls="no-margin"),
            P(
                "Prebuilt snippets cover navigation, hero stacks, and dashboard layouts so you can focus on your product.",
                cls="secondary-text",
            ),
            Div(
                SplitFeature(
                    eyebrow="Composable layouts",
                    title="Keep everything inside responsive containers",
                    description="Center content automatically with BeerCSS responsive helpers and consistent spacing tokens.",
                    image_src="https://via.placeholder.com/600x400/1e88e5/ffffff?text=Responsive",
                    cls="bg-secondary-container round shadow-small",
                ),
                SplitFeature(
                    eyebrow="Production polish",
                    title="Surface blur, shadows, and motion hooks are opt-in",
                    description="Material styling tokens are available by class; animations are disabled by default.",
                    image_src="https://via.placeholder.com/600x400/8e24aa/ffffff?text=Polish",
                    reverse=True,
                    cls="bg-secondary-container round shadow-small",
                ),
                cls="column gap-large",
            ),
            cls="column gap-large",
        ),
        cls="round bg-secondary-container shadow-medium large-padding",
    )

    grid_features = [
        {"icon": "dashboard", "title": "Page primitives", "description": "Hero, feature, pricing, and FAQ sections tuned for Material theming."},
        {"icon": "bolt", "title": "HTMX ready", "description": "Each preview runs live inside the notebook server for instant validation."},
        {"icon": "palette", "title": "Color tokens", "description": "Swap Material container classes to theme individual sections quickly."},
        {"icon": "extension", "title": "Composable APIs", "description": "All helpers accept extra classes so you can extend without forking."},
        {"icon": "security", "title": "Accessible defaults", "description": "Typography and spacing follow WCAG friendly defaults out of the box."},
        {"icon": "rocket_launch", "title": "Fast iteration", "description": "nbdev keeps code and docs together with automatic exports."},
    ]

    feature_grid_section = FeaturesGrid(
        features=grid_features,
        title="All the sections you need",
        subtitle="Mix heroes, feature highlights, grids, pricing, and FAQs without leaving the design system.",
        cols=3,
        cls="round shadow-medium large-padding",
    )

    faq_entries = [
        {"question": "Can I mix components?", "answer": "Yes. Every helper returns plain FastHTML nodes so you can reorder or nest them."},
        {"question": "How do colors work?", "answer": "Apply Material container classes such as bg-primary-container or surface-container-high to any wrapper."},
        {"question": "Is HTMX required?", "answer": "No. The interactions degrade gracefully, but HTMX hooks are available when you need them."},
    ]

    faq_section = FAQSection(
        title="Frequently asked questions",
        faqs=faq_entries,
        cls="round shadow-medium",
    )

    footer = PageFooter(
        columns=[
            {"title": "Product", "links": [{"text": "Components", "href": "#features"}, {"text": "Guides", "href": "/guides"}]},
            {"title": "Resources", "links": [{"text": "Docs", "href": "/docs"}, {"text": "Playground", "href": "/play"}]},
            {"title": "Company", "links": [{"text": "About", "href": "/about"}, {"text": "Contact", "href": "/contact"}]},
        ],
        copyright=f"(c) 2026 {brand_name}. All rights reserved.",
        social_links=[
            {"icon": "github", "href": "https://github.com"},
            {"icon": "twitter", "href": "https://twitter.com"},
            {"icon": "slack", "href": "https://slack.com"},
        ],
        logo=brand_name,
        cls="round shadow-medium large-padding",
    )

    toolbar_block = Div(toolbar, cls="row center-align bottom-margin")

    hero_block = Section(
        H2("Hero", cls="no-margin"),
        P("Primary pitch area with generous spacing.", cls="secondary-text"),
        hero_section,
        cls="round bg-primary-container shadow-medium column gap-medium large-padding",
    )

    features_block = Section(
        H2("Features", cls="no-margin"),
        P("Deep-dives for standout capabilities.", cls="secondary-text"),
        feature_highlights,
        cls="round bg-secondary-container shadow-medium column gap-medium large-padding",
    )

    feature_grid_block = Section(
        H2("Feature grid", cls="no-margin"),
        P("Icon cards for quick scanning.", cls="secondary-text"),
        feature_grid_section,
        cls="round bg-tertiary-container shadow-medium column gap-medium large-padding",
    )

    faq_block = Section(
        H2("FAQs", cls="no-margin"),
        P("Support answers in collapsible cards.", cls="secondary-text"),
        faq_section,
        cls="round surface-container-high shadow-medium column gap-medium large-padding",
    )

    footer_block = Section(
        H2("Footer", cls="no-margin"),
        P("Wrap up with key links and social proof.", cls="secondary-text"),
        footer,
        cls="round surface-container shadow-medium column gap-medium large-padding",
    )

    # Put layout classes on an inner wrapper; `Container(...)` provides centered width constraint.
    inner = Div(
        toolbar_block,
        hero_block,
        features_block,
        feature_grid_block,
        faq_block,
        footer_block,
        cls="responsive column gap-xlarge",
    )

    return Section(
        Container(inner),
        cls=f"bg-primary-container large-padding {cls}".strip(),
    )
