"""Pre-built landing page components for marketing websites and public-facing pages"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_web_pages.ipynb.

# %% auto 0
__all__ = ['HeroSection', 'FeaturesGrid', 'PricingSection', 'FAQSection', 'PageFooter', 'LandingNavBar']

# %% ../nbs/04_web_pages.ipynb 3
import importlib



from .components import *
from .core import *
from fasthtml.common import *
from .app_pages import *
from .foundations import *

from fastcore.utils import partial
from fasthtml.common import *
from fasthtml.jupyter import FastHTML, fast_app, JupyUvi, HTMX
from fastlite import *
import fasthtml.components as fc
from fasthtml.common import A, Button as FhButton, I, Span
import socket
import time
import subprocess

# %% ../nbs/04_web_pages.ipynb 6
def HeroSection(
    title: str,              # Main hero title
    subtitle: str,           # Hero subtitle/description
    primary_cta_text: str,   # Primary CTA button text
    primary_cta_href: str,   # Primary CTA button href
    secondary_cta_text: str = None,  # Secondary CTA button text (optional)
    secondary_cta_href: str = None,  # Secondary CTA button href (optional)
    background: str = "bg-primary-container",  # BeerCSS background class
    cls: str = "",  # Additional classes
    style: str | None = None,  # Optional inline style (avoid by default)
    extra_css: str | None = None,  # Optional custom CSS (minimal; opt-in)
    extra_js: str | None = None,  # Optional custom JS (minimal; opt-in)
 ):
    """Hero section (BeerCSS-first).
    
    Note: Avoid `middle-align` on the outer stack; in BeerCSS it can turn the
    wrapper into a horizontal flex row, which makes the H1/P/CTA sit side-by-side.
    """
    hooks = []
    if extra_css:
        hooks.append(Style(extra_css))
    if extra_js:
        hooks.append(Script(extra_js))
    
    ctas = [Button(primary_cta_text, href=primary_cta_href, variant="raised")]
    if secondary_cta_text and secondary_cta_href:
        ctas.append(Button(secondary_cta_text, href=secondary_cta_href, variant="outlined"))
    
    stack = DivVStacked(
        H1(title, cls="no-margin"),
        P(subtitle, cls="secondary-text"),
        Div(*ctas, cls="row middle-align center-align small-space"),
        cls="center-align large-padding",
    )
    content = Div(stack, cls="responsive")
    return Section(
        *hooks,
        content,
        cls=f"{background} {cls}".strip(),
        style=style,
    )

# %% ../nbs/04_web_pages.ipynb 9
def FeaturesGrid(
    features: list,  # List of dicts with 'icon', 'title', 'description'
    title: str = None,  # Optional section title
    subtitle: str = None,  # Optional section subtitle
    cols: int = 3,  # Number of columns (1-4)
    cls: str = ""  # Additional classes
):
    """Grid of feature cards using BeerCSS grid helpers."""
    import fh_matui.components as _cmp
    
    GridCell = getattr(_cmp, 'GridCell', None)
    ResponsiveGrid = getattr(_cmp, 'ResponsiveGrid', None)
    
    if GridCell is None or ResponsiveGrid is None:
        # Fallback: keep previews working even if the notebook kernel has a stale module import.
        def GridCell(*c, span=(), cls='', **kwargs):
            cell_cls = []
            cell_cls.extend(normalize_tokens(span))
            cell_cls.extend(normalize_tokens(cls))
            cell_cls = [t for t in cell_cls if t]
            return Div(*c, cls=stringify(dedupe_preserve_order(cell_cls)), **kwargs)
        
        def ResponsiveGrid(*cells, space='medium-space', cls: str = '', **kwargs):
            cls_tokens = normalize_tokens(cls)
            grid_cls = ['grid']
            if space and space not in cls_tokens:
                grid_cls.extend(normalize_tokens(space))
            grid_cls.extend(cls_tokens)
            grid_cls = [t for t in grid_cls if t]
            return Div(*cells, cls=stringify(dedupe_preserve_order(grid_cls)), **kwargs)
    
    cols = max(1, min(int(cols), 4))
    col_width = 12 // cols  # 12-col grid
    
    s_span = "s12"
    m_span = "m12" if cols == 1 else "m6"
    l_span = f"l{col_width}"
    cell_span = f"{s_span} {m_span} {l_span}".strip()
    
    cells = [
        GridCell(
            Card(
                Div(Icon(f["icon"], size="medium", cls="primary-text"), cls="center-align"),
                H5(f["title"], cls="center-align small-margin"),
                P(f["description"], cls="secondary-text center-align"),
                cls="center-align padding",
            ),
            span=cell_span,
        )
        for f in features
    ]
    
    content = []
    if title:
        content.append(H1(title, cls="center-align bottom-margin"))
    if subtitle:
        content.append(P(subtitle, cls="center-align secondary-text large-margin large-text"))
    
    content.append(ResponsiveGrid(*cells, space="medium-space"))
    return Section(*content, cls=f"padding horizontal-padding {cls}".strip())

# %% ../nbs/04_web_pages.ipynb 13
def PricingSection(

    title: str,
    price: str,
    plan_name: str,
    features: list,
    cta_text: str,
    cta_href: str,
    period: str = "month",
    cls: str = "",
):
    """Simple pricing card: title, bullets, button."""
    
    # Build feature list items
    feature_items = []
    for feature in features:
        feature_items.append(
            Li(
                Icon("check", cls="small primary-text"),
                Span(feature, cls="small-space"),
                cls="row middle-align small-space",
            )
        )
    
    # Build the card
    card = Card(
        # Header
        H3(plan_name, cls="center-align"),
        H2(price, cls="center-align no-margin"),
        P(f"per {period}", cls="center-align secondary-text"),
        
        # Features
        Ul(*feature_items, cls="no-margin"),
        
        # CTA
        Button(cta_text, href=cta_href, cls="responsive large-margin"),
        
        cls="medium-width padding round",
    )
    
    # Center the card on the page
    return Section(
        H2(title, cls="center-align"),
        Div(card, cls="center-align"),
        cls=f"padding {cls}".strip(),
    )

# %% ../nbs/04_web_pages.ipynb 16
def FAQSection(title: str, faqs: list, cls: str = ""):
    """FAQ section (BeerCSS-first).

    Goal: add a *small* vertical space between each question item (between <details> blocks).
    """
    items = [
        Div(
            Details(
                Summary(
                    Article(
                        Nav(Div(faq['question'], cls="max bold"), I("expand_more")),
                        cls="round primary no-elevate",
                    )
                ),
                Article(P(faq['answer'], cls="secondary-text"), cls="round border padding"),
            ),
            # Small visual gap between questions.
            cls="small-margin",
        )
        for faq in faqs
    ]
    
    return Section(
        H2(title, cls="center-align bottom-margin"),
        Div(*items, cls="column"),
        cls=f"responsive column {cls}".strip(),
    )

# %% ../nbs/04_web_pages.ipynb 19
def PageFooter(
    columns: list,         # List of dicts with 'title' and 'links' (list of dicts with 'text' and 'href')
    copyright: str,        # Copyright text
    social_links: list = None,  # List of dicts with 'icon' and 'href'
    logo: str = None,      # Optional logo text
    cls: str = ""          # Additional classes
):
    """Footer with multiple columns, social links, and copyright"""
    footer_cols = []
    
    # Logo column if provided
    if logo:
        footer_cols.append(
            Div(
                H6(logo, cls='no-margin bold'),
                cls='padding'
            )
        )
    
    # Link columns
    for col in columns:
        links = [A(link['text'], href=link['href'], cls='grey-text') for link in col.get('links', [])]
        footer_cols.append(
            Div(
                H6(col['title'], cls='no-margin bold'),
                Div(*links, cls='column small-space'),
                cls='padding'
            )
        )
    
    # Footer row with full spacing between columns
    footer_row = DivFullySpaced(*footer_cols)
    
    # Bottom section with copyright and social links
    bottom_left = Div(P(copyright, cls='small-text grey-text no-margin'))
    
    bottom_right = Div()
    if social_links:
        social_icons = [A(Icon(s['icon']), href=s['href'], cls='grey-text') for s in social_links]
        bottom_right = Div(*social_icons, cls='row small-space')
    
    bottom_section = DivFullySpaced(bottom_left, bottom_right)
    
    footer_cls = f'surface-container padding {cls}'.strip()
    return ft_hx('footer')(
        Div(
            footer_row,
            Hr(),
            bottom_section,
            cls=f"responsive {footer_cls}"
        )
    )


# %% ../nbs/04_web_pages.ipynb 21
def LandingNavBar(
    brand_name: str,        # Brand name for the navbar
    links: list = None,     # List of dicts with 'text' and 'href'
    actions: list = None,   # List of action buttons (Buttons/Links)
    sticky: bool = True,    # Whether navbar sticks to top
    cls: str = ""           # Additional classes
):
    """
    Landing page navigation bar using Toolbar component with brand and links.
    
    Args:
        brand_name: Brand name/logo text
        links: List of navigation links [{'text': 'Features', 'href': '#features'}, ...]
        actions: List of action elements (Buttons, etc.) for CTA
        sticky: Whether navbar sticks to top while scrolling (default: True)
        cls: Additional CSS classes
    
    Example:
        LandingNavBar(
            brand_name="MyBrand",
            links=[
                {'text': 'Features', 'href': '#features'},
                {'text': 'Pricing', 'href': '#pricing'},
                {'text': 'FAQ', 'href': '#faq'}
            ],
            actions=[
                Button("Sign Up", href="/signup", variant="raised")
            ]
        )
    """
    # Build navigation elements
    nav_items = []
    
    # Add brand
    nav_items.append(H5(brand_name, cls="no-margin bold"))
    
    # Add spacer to push links to the right
    nav_items.append(Div(cls="max"))
    
    # Add navigation links
    if links:
        for link in links:
            nav_items.append(
                A(link['text'], href=link['href'], cls="padding")
            )
    
    # Add action buttons
    if actions:
        nav_items.extend(actions)
    
    # Use Toolbar with sticky positioning and blur effect
    toolbar_cls = f"blur {'sticky top' if sticky else ''} {cls}".strip()
    
    return Toolbar(Container(*nav_items, responsive=True), cls=toolbar_cls, fill=True, elevate='medium')
